source 'https://rubygems.org'

gem 'jekyll', '~> 4.1.1'
gem 'liquid-c'

group :jekyll_plugins do
	gem 'jekyll-remote-theme'
	gem 'jekyll-sitemap'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]